version: "3.8"

services:

  db:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: 'question-app-db'
      MYSQL_USER: 'hp'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - questionApp-mysql

  questionApp-be:
    image: question-app-be
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/question-app-db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Turkey&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - questionApp-mysql
networks:
  questionApp-mysql: